version: "3.9"

services:
  api:
    build: ./flaskProject
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./flaskProject:/app   # Mount code vào container để hot reload
    environment:
      - FLASK_APP=app.py      
      - FLASK_ENV=development 
      - PYTHONPATH=/app
      - FLASK_DEBUG=1
    restart: unless-stopped